apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app.kubernetes.io/name: mt2
  name: mt2
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app.kubernetes.io/name: mt2
  template: 
    metadata: 
      labels: 
        app.kubernetes.io/name: mt2
    spec: 
      containers: 
        - 
          command: 
            - python
            - model_api.py
            - averaged-ende-export500k-v2
          image: mt2
          imagePullPolicy: IfNotPresent
          name: mt2
          ports: 
            - 
              containerPort: 8080
          resources: 
            limits: 
              memory: 2Gi
            requests: 
              memory: 600Mi
          volumeMounts: 
            - 
              mountPath: /host
              name: code
          workingDir: /host
      volumes: 
        - 
          hostPath: 
            path: /host
          name: code

